// src/constants/actionTypes.js


export const ADD_CHAT = 'ADD_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';

export const ADD_GENERAL_MESSAGE = 'ADD_GENERAL_MESSAGE';
export const UPDATE_GENERAL_MESSAGE = 'UPDATE_GENERAL_MESSAGE';
export const DELETE_GENERAL_MESSAGE = 'DELETE_GENERAL_MESSAGE';

export const ADD_SHARED_USER = 'ADD_SHARED_USER';
export const REMOVE_SHARED_USER = 'REMOVE_SHARED_USER';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_REPLY_TO_COMMENT = 'ADD_REPLY_TO_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_REPLY_FROM_COMMENT = 'DELETE_REPLY_FROM_COMMENT';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';

export const ADD_MEDIA = 'ADD_MEDIA';
export const REMOVE_MEDIA = 'REMOVE_MEDIA';

export const UPDATE_TASK_PROGRESS = 'UPDATE_TASK_PROGRESS';

export const ADD_VERSION = 'ADD_VERSION';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';

export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';

export const ADD_LINK = 'ADD_LINK';
export const REMOVE_LINK = 'REMOVE_LINK';

export const ADD_BOOKMARK_DATA = 'ADD_BOOKMARK_DATA';

export const ADD_COMMENTING_USER = 'ADD_COMMENTING_USER';
export const REMOVE_COMMENTING_USER = 'REMOVE_COMMENTING_USER';

export const ADD_COMMENT_REPLY = 'ADD_COMMENT_REPLY';
export const REMOVE_COMMENT_REPLY = 'REMOVE_COMMENT_REPLY';
